# Generated by Django 4.1 on 2022-08-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario'},
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='idade',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
