# Generated by Django 4.1 on 2022-08-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuarios_options_alter_usuarios_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=30),
        ),
    ]
