# Generated by Django 4.1 on 2022-08-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='preco_compra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativos',
            name='preco_venda',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
