# Generated by Django 4.1 on 2022-08-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_ativos_preco_compra_ativos_preco_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='verificar',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
