# Generated by Django 4.1 on 2022-08-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_ativos_verificar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ativos',
            old_name='verificar',
            new_name='intervalo_verificar',
        ),
    ]
