# Generated by Django 4.1 on 2022-08-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_remove_ativos_preco_compra_remove_ativos_preco_venda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='preco_compra',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ativos',
            name='preco_venda',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
