# Generated by Django 4.1 on 2022-08-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0006_ativos_preco_compra_ativos_preco_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='intervalo_verificar',
            field=models.IntegerField(default=0),
        ),
    ]
